# Generated by Django 2.1.7 on 2019-03-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displaynfib', '0002_auto_20190308_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiboutput',
            old_name='output',
            new_name='result',
        ),
        migrations.AlterField(
            model_name='fiboutput',
            name='time_taken',
            field=models.CharField(max_length=255),
        ),
    ]
